name: lint
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  golangci:
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.21.x']
        os: [ubuntu-latest]
    name: Lint
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }} 
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.52.2
        args: --timeout=5m
        only-new-issues: true
