name: test
on:
  workflow_dispatch:
  pull_request:
    types: [ assigned ]
  push:
jobs:
  test:
    strategy:
      matrix:
        go: [ '1.21.x' ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: go test -race -v -covermode atomic -coverprofile coverage.out ./...
